permalink: /:title.html
pygments: true

jekyll-press:
  exclude: 'feed/index.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
