version: "3"

services:
  jekyll_serve:
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=production
    command: ["jekyll", "serve"]
